[package]
name = "Simple_Port_Scanner"
version = "1.0.0"
edition = "2024"

[[bin]]
name = "sps"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
rayon = "1.11.0"
socket2 = {version =  "0.6.1", features = ["all"] }
etherparse = "0.19.0"
